// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _17: (x0,x1) => x0.get(x1),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _919: x0 => x0.headers,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1294: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1295: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1296: (x0,x1) => x0.createElement(x1),
      _1297: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1298: (x0,x1) => x0.removeAttribute(x1),
      _1299: (x0,x1) => x0.getAttribute(x1),
      _1303: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1313: x0 => x0.click(),
      _1314: x0 => x0.remove(),
      _1317: x0 => globalThis.URL.revokeObjectURL(x0),
      _1320: x0 => globalThis.URL.createObjectURL(x0),
      _1323: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1323(f,arguments.length,x0) }),
      _1324: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1324(f,arguments.length,x0) }),
      _1325: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1325(f,arguments.length,x0) }),
      _1326: (x0,x1) => x0.querySelector(x1),
      _1327: (x0,x1) => x0.append(x1),
      _1328: (x0,x1) => x0.replaceChildren(x1),
      _1329: () => new XMLHttpRequest(),
      _1330: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1331: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1332: (x0,x1) => x0.send(x1),
      _1333: x0 => x0.abort(),
      _1334: x0 => x0.getAllResponseHeaders(),
      _1335: (x0,x1,x2) => x0.close(x1,x2),
      _1337: x0 => x0.close(),
      _1339: (x0,x1) => x0.send(x1),
      _1340: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1340(f,arguments.length,x0) }),
      _1341: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1342: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1342(f,arguments.length,x0) }),
      _1343: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1343(f,arguments.length,x0) }),
      _1344: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1344(f,arguments.length,x0) }),
      _1345: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1345(f,arguments.length,x0) }),
      _1346: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1346(f,arguments.length,x0) }),
      _1347: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1347(f,arguments.length,x0) }),
      _1348: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1348(f,arguments.length,x0) }),
      _1349: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1349(f,arguments.length,x0) }),
      _1350: (x0,x1) => x0.end(x1),
      _1351: x0 => x0.pause(),
      _1352: x0 => x0.play(),
      _1353: x0 => x0.load(),
      _1354: (x0,x1) => x0.setSinkId(x1),
      _1355: x0 => x0.decode(),
      _1356: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1357: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1358: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1358(f,arguments.length,x0) }),
      _1359: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1359(f,arguments.length,x0) }),
      _1360: x0 => x0.send(),
      _1361: () => new XMLHttpRequest(),
      _1362: (x0,x1,x2) => x0.open(x1,x2),
      _1373: x0 => x0.releaseMediaPlayer(),
      _1374: (x0,x1) => globalThis.newPlayerInstance(x0,x1),
      _1375: x0 => x0.initializeMediaPlayer(),
      _1379: (x0,x1,x2,x3,x4,x5,x6) => x0.startPlayer(x1,x2,x3,x4,x5,x6),
      _1380: x0 => x0.stopPlayer(),
      _1384: (x0,x1) => x0.seekToPlayer(x1),
      _1392: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1392(f,arguments.length,x0,x1,x2) }),
      _1393: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1393(f,arguments.length,x0,x1) }),
      _1394: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1394(f,arguments.length,x0,x1) }),
      _1395: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1395(f,arguments.length,x0,x1) }),
      _1396: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1396(f,arguments.length,x0,x1,x2,x3) }),
      _1397: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1397(f,arguments.length,x0,x1,x2) }),
      _1398: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1398(f,arguments.length,x0,x1,x2) }),
      _1399: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1399(f,arguments.length,x0,x1,x2) }),
      _1400: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1400(f,arguments.length,x0,x1,x2) }),
      _1401: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1401(f,arguments.length,x0,x1,x2) }),
      _1402: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1402(f,arguments.length,x0) }),
      _1403: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1403(f,arguments.length,x0) }),
      _1404: (x0,x1) => x0.appendChild(x1),
      _1405: (x0,x1) => x0.isEncoderSupported(x1),
      _1406: x0 => x0.releaseFlautoRecorder(),
      _1407: (x0,x1) => globalThis.newRecorderInstance(x0,x1),
      _1408: x0 => x0.initializeFlautoRecorder(),
      _1410: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => x0.startRecorder(x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _1411: x0 => x0.stopRecorder(),
      _1417: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1417(f,arguments.length,x0,x1,x2) }),
      _1418: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1418(f,arguments.length,x0,x1,x2) }),
      _1419: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1419(f,arguments.length,x0,x1,x2) }),
      _1420: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1420(f,arguments.length,x0,x1,x2) }),
      _1421: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1421(f,arguments.length,x0,x1,x2,x3) }),
      _1422: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1422(f,arguments.length,x0,x1,x2) }),
      _1423: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1423(f,arguments.length,x0,x1,x2) }),
      _1429: x0 => ({audio: x0}),
      _1430: (x0,x1) => x0.getUserMedia(x1),
      _1431: x0 => x0.getAudioTracks(),
      _1432: x0 => x0.stop(),
      _1433: x0 => ({video: x0}),
      _1434: x0 => x0.getVideoTracks(),
      _1435: () => globalThis.Notification.requestPermission(),
      _1436: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1436(f,arguments.length,x0) }),
      _1437: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1437(f,arguments.length,x0) }),
      _1438: (x0,x1,x2) => x0.getCurrentPosition(x1,x2),
      _1447: (x0,x1) => x0.item(x1),
      _1448: () => new FileReader(),
      _1450: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1451: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1451(f,arguments.length,x0) }),
      _1452: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1453: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1453(f,arguments.length,x0) }),
      _1454: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1454(f,arguments.length,x0) }),
      _1455: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1455(f,arguments.length,x0) }),
      _1456: (x0,x1) => x0.removeChild(x1),
      _1458: () => new SpeechSynthesisUtterance(),
      _1459: x0 => x0.pause(),
      _1460: x0 => x0.resume(),
      _1461: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1461(f,arguments.length,x0) }),
      _1462: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1462(f,arguments.length,x0) }),
      _1463: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1463(f,arguments.length,x0) }),
      _1464: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1464(f,arguments.length,x0) }),
      _1465: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1465(f,arguments.length,x0) }),
      _1466: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1466(f,arguments.length,x0) }),
      _1467: (x0,x1) => x0.speak(x1),
      _1468: x0 => x0.cancel(),
      _1469: x0 => x0.getVoices(),
      _1470: Date.now,
      _1472: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1473: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1474: () => new Error().stack,
      _1475: () => typeof dartUseDateNowForTicks !== "undefined",
      _1476: () => 1000 * performance.now(),
      _1477: () => Date.now(),
      _1478: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1479: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1480: () => new WeakMap(),
      _1481: (map, o) => map.get(o),
      _1482: (map, o, v) => map.set(o, v),
      _1483: (exn) => exn.toString(),
      _1484: (exn) => exn.stack,
      _1485: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1486: x0 => new WeakRef(x0),
      _1487: x0 => x0.deref(),
      _1494: () => globalThis.WeakRef,
      _1498: s => JSON.stringify(s),
      _1499: s => printToConsole(s),
      _1500: (o, p, r) => o.replaceAll(p, () => r),
      _1501: (o, p, r) => o.replace(p, () => r),
      _1502: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1503: s => s.toUpperCase(),
      _1504: s => s.trim(),
      _1505: s => s.trimLeft(),
      _1506: s => s.trimRight(),
      _1507: (string, times) => string.repeat(times),
      _1508: Function.prototype.call.bind(String.prototype.indexOf),
      _1509: (s, p, i) => s.lastIndexOf(p, i),
      _1510: (string, token) => string.split(token),
      _1511: Object.is,
      _1514: (o, t) => typeof o === t,
      _1515: (o, c) => o instanceof c,
      _1516: o => Object.keys(o),
      _1517: (o,s) => o[s],
      _1518: (o,s,v) => o[s] = v,
      _1519: (o, a) => o + a,
      _1546: x0 => new Array(x0),
      _1548: x0 => x0.length,
      _1550: (x0,x1) => x0[x1],
      _1551: (x0,x1,x2) => { x0[x1] = x2 },
      _1554: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1556: x0 => new Int8Array(x0),
      _1557: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1559: x0 => new Uint8ClampedArray(x0),
      _1561: x0 => new Int16Array(x0),
      _1563: x0 => new Uint16Array(x0),
      _1565: x0 => new Int32Array(x0),
      _1567: x0 => new Uint32Array(x0),
      _1569: x0 => new Float32Array(x0),
      _1571: x0 => new Float64Array(x0),
      _1594: () => Symbol("jsBoxedDartObjectProperty"),
      _1595: x0 => x0.random(),
      _1596: (x0,x1) => x0.getRandomValues(x1),
      _1597: () => globalThis.crypto,
      _1598: () => globalThis.Math,
      _1611: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1612: (handle) => clearTimeout(handle),
      _1613: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1614: (handle) => clearInterval(handle),
      _1615: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1616: () => Date.now(),
      _1617: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1618: (x0,x1) => x0.exec(x1),
      _1619: (x0,x1) => x0.test(x1),
      _1620: x0 => x0.pop(),
      _1622: o => o === undefined,
      _1624: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1626: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1627: o => o instanceof RegExp,
      _1628: (l, r) => l === r,
      _1629: o => o,
      _1630: o => o,
      _1631: o => o,
      _1632: b => !!b,
      _1633: o => o.length,
      _1635: (o, i) => o[i],
      _1636: f => f.dartFunction,
      _1637: () => ({}),
      _1638: () => [],
      _1640: () => globalThis,
      _1641: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1642: (o, p) => p in o,
      _1643: (o, p) => o[p],
      _1644: (o, p, v) => o[p] = v,
      _1645: (o, m, a) => o[m].apply(o, a),
      _1647: o => String(o),
      _1648: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1649: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1649(f,arguments.length,x0) }),
      _1650: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1650(f,arguments.length,x0,x1) }),
      _1651: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1652: o => [o],
      _1653: (o0, o1) => [o0, o1],
      _1654: (o0, o1, o2) => [o0, o1, o2],
      _1655: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1656: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1657: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1658: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1659: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1660: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1661: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1662: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1663: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1664: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1665: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1666: x0 => new ArrayBuffer(x0),
      _1667: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1669: x0 => x0.index,
      _1670: x0 => x0.groups,
      _1671: x0 => x0.flags,
      _1672: x0 => x0.multiline,
      _1673: x0 => x0.ignoreCase,
      _1674: x0 => x0.unicode,
      _1675: x0 => x0.dotAll,
      _1676: (x0,x1) => { x0.lastIndex = x1 },
      _1677: (o, p) => p in o,
      _1678: (o, p) => o[p],
      _1679: (o, p, v) => o[p] = v,
      _1682: x0 => x0.send(),
      _1684: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1684(f,arguments.length,x0) }),
      _1685: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1685(f,arguments.length,x0) }),
      _1690: x0 => new Blob(x0),
      _1691: x0 => ({type: x0}),
      _1692: (x0,x1) => new Blob(x0,x1),
      _1693: (x0,x1,x2) => x0.open(x1,x2),
      _1694: (x0,x1) => new WebSocket(x0,x1),
      _1695: (x0,x1) => x0.getResponseHeader(x1),
      _1698: () => new AbortController(),
      _1699: x0 => x0.abort(),
      _1700: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1701: (x0,x1) => globalThis.fetch(x0,x1),
      _1702: (x0,x1) => x0.get(x1),
      _1703: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1703(f,arguments.length,x0,x1,x2) }),
      _1704: (x0,x1) => x0.forEach(x1),
      _1705: x0 => x0.getReader(),
      _1706: x0 => x0.cancel(),
      _1707: x0 => x0.read(),
      _1709: o => o instanceof Array,
      _1710: (a, i) => a.push(i),
      _1711: (a, i) => a.splice(i, 1)[0],
      _1714: a => a.pop(),
      _1715: (a, i) => a.splice(i, 1),
      _1716: (a, s) => a.join(s),
      _1717: (a, s, e) => a.slice(s, e),
      _1719: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1720: a => a.length,
      _1722: (a, i) => a[i],
      _1723: (a, i, v) => a[i] = v,
      _1725: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1726: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1728: o => o instanceof Uint8Array,
      _1729: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1730: o => o instanceof Int8Array,
      _1731: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1732: o => o instanceof Uint8ClampedArray,
      _1733: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1734: o => o instanceof Uint16Array,
      _1735: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1736: o => o instanceof Int16Array,
      _1737: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1738: o => o instanceof Uint32Array,
      _1739: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1740: o => o instanceof Int32Array,
      _1741: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1743: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1744: o => o instanceof Float32Array,
      _1745: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1746: o => o instanceof Float64Array,
      _1747: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1748: (t, s) => t.set(s),
      _1749: l => new DataView(new ArrayBuffer(l)),
      _1750: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1751: o => o.byteLength,
      _1752: o => o.buffer,
      _1753: o => o.byteOffset,
      _1754: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1755: (b, o) => new DataView(b, o),
      _1756: (b, o, l) => new DataView(b, o, l),
      _1757: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1758: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1759: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1760: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1761: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1762: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1763: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1764: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1765: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1766: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1767: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1768: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1771: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1772: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1773: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1774: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1775: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1776: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1777: Function.prototype.call.bind(Number.prototype.toString),
      _1778: Function.prototype.call.bind(BigInt.prototype.toString),
      _1779: Function.prototype.call.bind(Number.prototype.toString),
      _1780: (d, digits) => d.toFixed(digits),
      _1791: () => globalThis.document,
      _1797: (x0,x1) => { x0.height = x1 },
      _1799: (x0,x1) => { x0.width = x1 },
      _1801: (x0,x1) => { x0.pointerEvents = x1 },
      _1810: x0 => x0.style,
      _1813: x0 => x0.src,
      _1814: (x0,x1) => { x0.src = x1 },
      _1815: x0 => x0.naturalWidth,
      _1816: x0 => x0.naturalHeight,
      _1832: x0 => x0.status,
      _1833: (x0,x1) => { x0.responseType = x1 },
      _1835: x0 => x0.response,
      _1872: x0 => x0.readyState,
      _1874: (x0,x1) => { x0.timeout = x1 },
      _1876: (x0,x1) => { x0.withCredentials = x1 },
      _1877: x0 => x0.upload,
      _1878: x0 => x0.responseURL,
      _1879: x0 => x0.status,
      _1880: x0 => x0.statusText,
      _1882: (x0,x1) => { x0.responseType = x1 },
      _1883: x0 => x0.response,
      _1884: x0 => x0.responseText,
      _1895: x0 => x0.loaded,
      _1896: x0 => x0.total,
      _1943: (x0,x1) => { x0.draggable = x1 },
      _1959: x0 => x0.style,
      _1972: (x0,x1) => { x0.oncancel = x1 },
      _1978: (x0,x1) => { x0.onchange = x1 },
      _2018: (x0,x1) => { x0.onerror = x1 },
      _2174: (x0,x1) => { x0.href = x1 },
      _2318: (x0,x1) => { x0.download = x1 },
      _2343: (x0,x1) => { x0.href = x1 },
      _2561: x0 => x0.error,
      _2562: x0 => x0.src,
      _2563: (x0,x1) => { x0.src = x1 },
      _2571: (x0,x1) => { x0.preload = x1 },
      _2572: x0 => x0.buffered,
      _2575: x0 => x0.currentTime,
      _2576: (x0,x1) => { x0.currentTime = x1 },
      _2577: x0 => x0.duration,
      _2582: (x0,x1) => { x0.playbackRate = x1 },
      _2595: (x0,x1) => { x0.volume = x1 },
      _2612: x0 => x0.code,
      _2613: x0 => x0.message,
      _2687: x0 => x0.length,
      _2883: (x0,x1) => { x0.accept = x1 },
      _2897: x0 => x0.files,
      _2923: (x0,x1) => { x0.multiple = x1 },
      _2941: (x0,x1) => { x0.type = x1 },
      _3191: (x0,x1) => { x0.src = x1 },
      _3197: (x0,x1) => { x0.async = x1 },
      _3659: () => globalThis.window,
      _3702: x0 => x0.location,
      _3717: x0 => x0.opener,
      _3721: x0 => x0.navigator,
      _3996: x0 => x0.protocol,
      _4000: x0 => x0.hostname,
      _4002: x0 => x0.port,
      _4089: x0 => x0.geolocation,
      _4092: x0 => x0.mediaDevices,
      _4094: x0 => x0.permissions,
      _4095: x0 => x0.maxTouchPoints,
      _4105: x0 => x0.platform,
      _4108: x0 => x0.userAgent,
      _4109: x0 => x0.vendor,
      _4112: x0 => x0.language,
      _4113: x0 => x0.languages,
      _4159: x0 => x0.data,
      _4533: x0 => x0.readyState,
      _4546: (x0,x1) => { x0.binaryType = x1 },
      _4549: x0 => x0.code,
      _4550: x0 => x0.reason,
      _6211: x0 => x0.type,
      _6212: x0 => x0.target,
      _6252: x0 => x0.signal,
      _6313: x0 => x0.firstChild,
      _6324: () => globalThis.document,
      _6406: x0 => x0.body,
      _6408: x0 => x0.head,
      _6737: (x0,x1) => { x0.id = x1 },
      _6760: x0 => x0.innerHTML,
      _6761: (x0,x1) => { x0.innerHTML = x1 },
      _6764: x0 => x0.children,
      _8083: x0 => x0.value,
      _8085: x0 => x0.done,
      _8265: x0 => x0.size,
      _8266: x0 => x0.type,
      _8272: x0 => x0.name,
      _8273: x0 => x0.lastModified,
      _8278: x0 => x0.length,
      _8283: x0 => x0.result,
      _8780: x0 => x0.url,
      _8782: x0 => x0.status,
      _8784: x0 => x0.statusText,
      _8785: x0 => x0.headers,
      _8786: x0 => x0.body,
      _9574: x0 => x0.active,
      _11187: (x0,x1) => { x0.display = x1 },
      _12409: x0 => x0.name,
      _13156: () => globalThis.speechSynthesis,
      _13157: (x0,x1) => { x0.lang = x1 },
      _13159: (x0,x1) => { x0.pitch = x1 },
      _13162: (x0,x1) => { x0.rate = x1 },
      _13164: (x0,x1) => { x0.text = x1 },
      _13165: (x0,x1) => { x0.voice = x1 },
      _13166: x0 => x0.voice,
      _13168: (x0,x1) => { x0.volume = x1 },
      _13169: (x0,x1) => { x0.onstart = x1 },
      _13170: (x0,x1) => { x0.onend = x1 },
      _13171: (x0,x1) => { x0.onpause = x1 },
      _13172: (x0,x1) => { x0.onresume = x1 },
      _13173: (x0,x1) => { x0.onerror = x1 },
      _13174: (x0,x1) => { x0.onboundary = x1 },
      _13176: x0 => x0.lang,
      _13177: x0 => x0.localService,
      _13178: x0 => x0.name,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      s: [
        "([ \r\n\t]+)|([!-\\[\\]-‧‪-퟿豈-￿][̀-ͯ]*|[\ud800-\udbff][\udc00-\udfff][̀-ͯ]*|\\\\verb\\*([^]).*?\\3|\\\\verb([^*a-zA-Z]).*?\\4|\\\\operatorname\\*|\\\\[a-zA-Z@]+[ \r\n\t]*|\\\\[^\ud800-\udfff])",
      ],
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
